apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
    tier: service
spec:
  selector:
    app: products
    tier: micro
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    tier: service
spec:
  selector:
    app: orders
    tier: micro
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    tier: service
spec:
  type: LoadBalancer
  selector:
    app: auth
    tier: micro
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: outer-service
  labels:
    app: outer-service
    tier: service
spec:
  selector:
    app: api
    tier: api
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30500
